CREATE TABLE [dbo].[Usuarios]
(
	UsuariosId INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Usuarios PRIMARY KEY CLUSTERED(UsuariosId)
,   Usuario VARCHAR(250) NOT NULL
,   Nombre  VARCHAR(500) NOT NULL
,   Contrasena VARCHAR(250) NOT NULL
,   Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION=PAGE)
GO
